"""CoreSDK protobuf stubs.

Generated stubs (from buf) are preferred when available.
Falls back to hand-written dataclass stubs if grpcio-tools is not installed.
"""
from __future__ import annotations

try:
    # Generated by buf (run core-sdk/scripts/gen-proto.sh to regenerate)
    from coresdk.gen.coresdk.v1 import (  # noqa: F401
        auth_pb2,
        policy_pb2,
    )
    _GENERATED = True
except ImportError:
    # Fallback: hand-written dataclass stubs (no buf/grpcio-tools needed)
    from coresdk._proto import auth_pb2 as auth_pb2  # type: ignore[no-redef]  # noqa: F401
    from coresdk._proto import policy_pb2 as policy_pb2  # type: ignore[no-redef]  # noqa: F401
    _GENERATED = False

__all__ = ["auth_pb2", "policy_pb2", "_GENERATED"]
